[project]
name = "evaluation-kt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.15.0",
    "deepagents>=0.7.15",
    "fastapi>=0.141.1",
    "httpx>=0.28.1",
    "langchain>=1.4.1",
    "langchain-core>=1.6.3",
    "langchain-openai>=1.6.2",
    "langgraph>=1.2.11",
    "langsmith>=0.13.0",
    "openai>=3.14.1",
    "pydantic>=2.13.5",
    "pydantic-settings>=2.15.0",
    "python-docx>=1.2.0",
    "tavily-python>=0.8.4",
    "uvicorn[standard]>=0.53.0",
    "websockets>=16.1.1",
]
